# Generated by Django 4.1.5 on 2023-02-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задачу', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Выполнено?'),
            preserve_default=False,
        ),
    ]
