# Generated by Django 4.1.5 on 2023-02-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_options_task_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='flag',
            field=models.IntegerField(choices=[(1, 'Легко'), (2, 'Средне'), (3, 'Сложно')], default=1, verbose_name='Флаг'),
        ),
    ]
