# Generated by Django 4.1.5 on 2023-02-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Выполнено?'),
        ),
    ]
