# Generated by Django 4.1.5 on 2023-02-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_task_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Избранное?'),
        ),
    ]
