# Generated by Django 4.1.5 on 2023-02-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_task_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_create',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='task',
            name='date_finish',
            field=models.DateField(null=True, verbose_name='Дата завершения'),
        ),
    ]
