# Generated by Django 4.1.5 on 2023-02-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_task_date_create_task_date_finish'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Прикрепленный файл к задаче')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task', verbose_name='Прикрепленная задача')),
            ],
        ),
    ]
