# Generated by Django 4.1.5 on 2023-02-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_filestask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filestask',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AddField(
            model_name='filestask',
            name='filename',
            field=models.CharField(default='asd', max_length=150, verbose_name='Имя файла'),
            preserve_default=False,
        ),
    ]
