# Generated by Django 4.1.5 on 2023-02-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_filestask_options_filestask_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='custom_flags',
            field=models.JSONField(null=True, verbose_name='Флаги пользователя'),
        ),
    ]
