# Generated by Django 4.1.5 on 2023-02-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_task_custom_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='flag',
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Легко'), (2, 'Средне'), (3, 'Сложно')], default=1, verbose_name='Сложность'),
        ),
    ]
