# Generated by Django 4.1.5 on 2023-02-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_task_flag_task_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='difficulty',
            new_name='flag',
        ),
    ]
