# Generated by Django 4.1.5 on 2023-03-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='custom_flags',
            field=models.JSONField(default='[]', null=True, verbose_name='Флаги пользователя'),
        ),
    ]
