# Generated by Django 4.1.5 on 2023-03-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_task_custom_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='custom_flags',
            field=models.JSONField(default=list, null=True, verbose_name='Флаги пользователя'),
        ),
    ]
